

function TestComponent() {


    return (
        <div className="clearfix">
            <figure className="figure float-start col-3">
                <img className="figure-img img-fluid rounded" src="https://fastly.picsum.photos/id/288/300/300.jpg?hmac=7RMC2BTzA6EpogvGf74Us4VguwkoeSsLzBARJbs5VOk" alt="SomeImg" />
                <figcaption className="figure-caption">Some caption for my image</figcaption>
            </figure>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, quas laboriosam obcaecati itaque quidem dolorum tempora doloribus deleniti sint minus cumque sequi cum sunt expedita vel commodi dicta error totam ut? Deserunt rerum voluptatum explicabo aliquid autem similique fuga repudiandae. Adipisci qui dignissimos eaque, eligendi architecto suscipit id hic saepe provident porro enim molestiae consequuntur est praesentium eos deserunt pariatur optio sed itaque vitae? Animi sed accusamus id odit, minus magni voluptatum cumque. Velit dolores voluptas soluta dolore eaque sunt natus amet commodi minus quia esse quibusdam a deleniti, suscipit ducimus molestias ipsum dolorem error repellendus quos, incidunt culpa! Sit assumenda enim a, temporibus delectus cumque eaque minus nisi facilis unde, cupiditate eos tempora blanditiis illo in, quibusdam ipsam non praesentium autem recusandae asperiores! Impedit eius reprehenderit odit quibusdam magni at beatae laboriosam cumque quis, cum laudantium suscipit eum provident accusantium numquam similique alias ducimus tempora odio nulla, iure vel quidem aut. Iste, exercitationem illo. Doloribus fuga nemo accusamus eaque error modi asperiores reiciendis ratione voluptatum mollitia eveniet, dolores rerum vero alias ex maxime? Rem sed minima sunt dolorum optio nihil aut illum harum laborum consectetur? Error illum ipsum voluptas, quaerat temporibus amet inventore maiores aspernatur adipisci assumenda id ipsam.</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, quas laboriosam obcaecati itaque quidem dolorum tempora doloribus deleniti sint minus cumque sequi cum sunt expedita vel commodi dicta error totam ut? Deserunt rerum voluptatum explicabo aliquid autem similique fuga repudiandae. Adipisci qui dignissimos eaque, eligendi architecto suscipit id hic saepe provident porro enim molestiae consequuntur est praesentium eos deserunt pariatur optio sed itaque vitae? Animi sed accusamus id odit, minus magni voluptatum cumque. Velit dolores voluptas soluta dolore eaque sunt natus amet commodi minus quia esse quibusdam a deleniti, suscipit ducimus molestias ipsum dolorem error repellendus quos, incidunt culpa! Sit assumenda enim a, temporibus delectus cumque eaque minus nisi facilis unde, cupiditate eos tempora blanditiis illo in, quibusdam ipsam non praesentium autem recusandae asperiores! Impedit eius reprehenderit odit quibusdam magni at beatae laboriosam cumque quis, cum laudantium suscipit eum provident accusantium numquam similique alias ducimus tempora odio nulla, iure vel quidem aut. Iste, exercitationem illo. Doloribus fuga nemo accusamus eaque error modi asperiores reiciendis ratione voluptatum mollitia eveniet, dolores rerum vero alias ex maxime? Rem sed minima sunt dolorum optio nihil aut illum harum laborum consectetur? Error illum ipsum voluptas, quaerat temporibus amet inventore maiores aspernatur adipisci assumenda id ipsam.</p>

            <img className="float-end" src="https://fastly.picsum.photos/id/288/300/300.jpg?hmac=7RMC2BTzA6EpogvGf74Us4VguwkoeSsLzBARJbs5VOk" alt="SomeImg" />
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ad, quas laboriosam obcaecati itaque quidem dolorum tempora doloribus deleniti sint minus cumque sequi cum sunt expedita vel commodi dicta error totam ut? Deserunt rerum voluptatum explicabo aliquid autem similique fuga repudiandae. Adipisci qui dignissimos eaque, eligendi architecto suscipit id hic saepe provident porro enim molestiae consequuntur est praesentium eos deserunt pariatur optio sed itaque vitae? Animi sed accusamus id odit, minus magni voluptatum cumque. Velit dolores voluptas soluta dolore eaque sunt natus amet commodi minus quia esse quibusdam a deleniti, suscipit ducimus molestias ipsum dolorem error repellendus quos, incidunt culpa! Sit assumenda enim a, temporibus delectus cumque eaque minus nisi facilis unde, cupiditate eos tempora blanditiis illo in, quibusdam ipsam non praesentium autem recusandae asperiores! Impedit eius reprehenderit odit quibusdam magni at beatae laboriosam cumque quis, cum laudantium suscipit eum provident accusantium numquam similique alias ducimus tempora odio nulla, iure vel quidem aut. Iste, exercitationem illo. Doloribus fuga nemo accusamus eaque error modi asperiores reiciendis ratione voluptatum mollitia eveniet, dolores rerum vero alias ex maxime? Rem sed minima sunt dolorum optio nihil aut illum harum laborum consectetur? Error illum ipsum voluptas, quaerat temporibus amet inventore maiores aspernatur adipisci assumenda id ipsam.</p>
        </div>
    );
}

export default TestComponent;